### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by eddyparkinson** [nodeit/express-shopify-webhooks#1]
I am struggling to workout the directory structure you used. 
A video of this being setup would help a lot. 

**Require Error**
At line : node_modules\express-shopify-webhooks\lib\express-shopify-webhooks.js:74:55
Error: Cannot find module 'express_shopify_webhooks\webhook_handlers\app.js'

with require:
>The path is relative to the directory in which you are requiring the files

so I assume "webhook_handlers" folder needs to be in a sub dir or maybe in node_modules.

**Comment by nodeit** [comment]
The webhook_handlers should be a sub dir in your project, not in node_modules. 

e.g.:
- app.js
- webhooks
-- products.js

This is not a repo that I actively maintain and unfortunately I do not have the bandwidth to create a video for this.
